# Generated by Django 3.2 on 2024-06-23 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('IN', 'India'), ('NP', 'Nepal'), ('BT', 'Bhutan')], default='IN', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_paper_link', models.CharField(default='Maharashtra', max_length=500)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.country')),
            ],
        ),
        migrations.CreateModel(
            name='Exhibition_Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('slug', models.SlugField(editable=False, max_length=40)),
                ('model_link', models.CharField(default='/model/', max_length=100)),
                ('poster', models.FileField(default='uploads/Poster/eyrcs2023.png', upload_to='uploads/Poster')),
                ('exhibition_front_view', models.FileField(default='uploads/Exhibition_front_view/eyrcs2023.png', upload_to='uploads/Exhibition_front_view')),
                ('description', models.TextField()),
                ('explanation_video_link', models.CharField(default='/', max_length=500)),
                ('research_paper_link', models.CharField(default='/', max_length=500)),
                ('animation_video', models.FileField(default='uploads/Poster/eyrcs2023.png', upload_to='uploads/Animation_Video')),
                ('exhibit_model', models.FileField(default='uploads/Poster/eyrcs2023.png', upload_to='uploads/Exhibition_Walls')),
                ('team_members', models.TextField()),
                ('school_name', models.CharField(blank=True, default='', max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.state')),
            ],
        ),
    ]
