# Generated by Django 3.2 on 2024-06-23 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state',
            old_name='research_paper_link',
            new_name='state',
        ),
    ]
