# Generated by Django 3.2 on 2024-06-23 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_rename_research_paper_link_state_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='country',
        ),
        migrations.AddField(
            model_name='exhibition_entry',
            name='country',
            field=models.CharField(choices=[('IN', 'India'), ('NP', 'Nepal'), ('BT', 'Bhutan')], default='IN', max_length=2),
        ),
        migrations.AlterField(
            model_name='exhibition_entry',
            name='state',
            field=models.CharField(blank=True, choices=[], max_length=2),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
