# Generated by Django 3.2 on 2024-06-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_auto_20240623_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition_entry',
            name='state',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
