# Generated by Django 3.2 on 2024-06-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_alter_exhibition_entry_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition_entry',
            name='state',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
