# Generated by Django 3.2 on 2024-06-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_alter_exhibition_entry_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition_entry',
            name='state',
            field=models.CharField(default='Maharashtra', max_length=20),
        ),
    ]
