# Generated by Django 3.2 on 2024-07-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0006_alter_exhibition_entry_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition_entry',
            name='animation_video',
            field=models.FileField(default='uploads/Exhibition_front_view/image6.jpg', upload_to='uploads/Animation_Video'),
        ),
        migrations.AlterField(
            model_name='exhibition_entry',
            name='exhibit_model',
            field=models.FileField(default='uploads/Exhibition_front_view/image6.jpg', upload_to='uploads/Exhibition_Walls'),
        ),
        migrations.AlterField(
            model_name='exhibition_entry',
            name='exhibition_front_view',
            field=models.FileField(default='uploads/Exhibition_front_view/image6.jpg', upload_to='uploads/Exhibition_front_view/'),
        ),
        migrations.AlterField(
            model_name='exhibition_entry',
            name='poster',
            field=models.FileField(default='uploads/Exhibition_front_view/image6.jpg', upload_to='uploads/Exhibition_front_view/'),
        ),
        migrations.AlterField(
            model_name='exhibition_entry',
            name='state',
            field=models.CharField(choices=[('JK', 'Jammu and Kashmir'), ('PB', 'Punjab'), ('MH', 'Maharashtra'), ('KA', 'Karnataka'), ('KL', 'Kerala'), ('TG', 'Telangana'), ('TN', 'Tamil Nadu'), ('MP', 'Madhya Pradesh'), ('BA', 'Bagmati'), ('JA', 'Janakpur'), ('34', 'Shemgang')], default='Maharashtra', max_length=20),
        ),
    ]
